# Generated by Django 3.2.5 on 2021-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scm_users',
            },
        ),
    ]
