# Generated by Django 3.2.5 on 2021-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
