# Generated by Django 3.2.5 on 2021-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
